name: 'dbt_yugioh'
version: '1.0.0'

profile: 'dbt_yugioh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
    example:
      +materialized: view
